### ISSUE TITLE
Set up Postgres db locally and change Rails to use Postgres

### ISSUE THREAD

**Issue by sarahpaz** [sarahpaz/pineappler#4]

**Comment by omenking** [comment]
- [ ] I would recommend installing Table Plus so you can easily view the database on your computer:
https://tableplus.com/

- [ ] To install postgres you may want to use homebrew. 
https://brew.sh/


- [ ] When you have homebrew install here is the commands
https://wiki.postgresql.org/wiki/Homebrew

Install postgres can be an **error-prone** experience. Fingers crossed🤞

- [ ] The database.yml should look something like this:

```
development:
  adapter: postgresql
  encoding: utf8

test: &test
  adapter: postgresql
  encoding: utf8

production:
  adapter: postgresql
  encoding: utf8

cucumber:
  <<: *test
```

Instead of passing in the credentials of the database username and password you'll want to instead pass along a connection_url via configuration variables.

Check out configuring a database
https://edgeguides.rubyonrails.org/configuring.html#configuring-a-database

- [ ] You'll need somewhere to store environment variables so you'll want to install figaro

https://github.com/laserlemon/figaro


- [ ] Once figaro is installed you'll want to add DATABASE_URL and your postgres connection URL to the `config/application.yml`
